name: Binary search - Typecheck (Mypy)

on:
  push

jobs:
  py-mypy:
    name: Binary search - Typecheck and Formatting check (Mypy)
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - run: pip install mypy
    - run: pip install black

    - run: mypy binary-search-typed.py
    
    # --check fails if black would reformat, succeeds if no changes
    - run: black --check binary-search-typed.py
